spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret_key: ${SECRET_KEY}


cors:
  allowed-origins: http://localhost:4200
  allowed-methods: POST, GET, PUT, DELETE, OPTIONS
  allowed-headers: "*"
